SSD_CATEGORIES = ["HDD, SSD ir priedai", "Vidiniai SSD diskai", "Vidiniai HDD diskai"]
COOLER_CATEGORIES = ["Aušintuvai", "Procesorių aušintuvai", "Korpusų aušintuvai"]
CASE_CATEGORIES = ["Korpusai ir priedai", "Korpusai"]
PSU_CATEGORIES = ["Maitinimo blokai", "Maitinimo blokai (PSU)"]
RAM_CATEGORIES = ["Operatyvinė atmintis (RAM)", "Operatyvinė atmintis (RAM)"]
MOTHERBOARD_CATEGORIES = ["Pagrindinės plokštės ir priedai", "Pagrindinės plokštės (MB)"]
CPU_CATEGORIES = ["Procesoriai (CPU)"]
GPU_CATEGORIES = ["Vaizdo plokštės ir priedai", "Vaizdo plokštės (GPU)"]
